USE [corporerm]
GO

/****** Object:  UserDefinedFunction [dbo].[FN_HORA_ALUNO_PRESENCIAL_EB]    Script Date: 27/04/2023 19:28:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [dbo].[FN_HORA_ALUNO_PRESENCIAL_EB] (

	@CODCOLIGADA INT, 
	@IDPERLET INT,
	@IDHABILITACAOFILIAL INT,
	@IDTURMADISC INT,
	@RA VARCHAR (20),
	@CODCURSO VARCHAR (10),
	@TIPO VARCHAR (1),
	@MES VARCHAR(2),
	@ANO VARCHAR(4)

) RETURNS INT

/********************************************************************
* AUTOR:   Ricardo Dantas
* DATA:    14/04/2023
* DESCRICAO: Função que retorna a data de saída do aluno
*********************************************************************/


BEGIN         
	DECLARE 
		@HORA_ALUNO INT

	IF @TIPO = 'P'
	BEGIN
		SELECT
			@HORA_ALUNO = SUM(DATEDIFF(HOUR,SHORARIO.HORAINICIAL,SHORARIO.HORAFINAL))
		FROM SMATRICPL WITH (NOLOCK)
		LEFT JOIN SMATRICULA WITH (NOLOCK)
			ON SMATRICULA.CODCOLIGADA = SMATRICPL.CODCOLIGADA
			AND SMATRICULA.IDPERLET = SMATRICPL.IDPERLET
			AND SMATRICULA.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
			AND SMATRICULA.RA = SMATRICPL.RA
		LEFT JOIN STURMADISC WITH (NOLOCK)
			ON STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
			AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
		LEFT JOIN SPLANOAULA WITH (NOLOCK)
			ON STURMADISC.CODCOLIGADA = SPLANOAULA.CODCOLIGADA
			AND STURMADISC.IDTURMADISC = SPLANOAULA.IDTURMADISC
		LEFT JOIN SHORARIO WITH (NOLOCK)
			ON SHORARIO.CODCOLIGADA = SPLANOAULA.CODCOLIGADA
			AND SHORARIO.CODHOR = SPLANOAULA.CODHOR
		WHERE 
			SMATRICPL.CODCOLIGADA = @CODCOLIGADA
		AND	SMATRICPL.IDPERLET = @IDPERLET
		AND	SMATRICPL.IDHABILITACAOFILIAL = @IDHABILITACAOFILIAL
		AND	SMATRICPL.RA = @RA
		AND STURMADISC.IDTURMADISC = @IDTURMADISC
		AND	MONTH(SPLANOAULA.DATA) = @MES
		AND	YEAR(SPLANOAULA.DATA) = @ANO
		AND SPLANOAULA.DATA >= ISNULL((SELECT datEfetivacaoMatricula FROM [dbo].[FN_RETORNA_DATA_MOV_MATRICULA_EB](
										@CODCOLIGADA,@IDPERLET,@IDHABILITACAOFILIAL,@RA))
									,EOMONTH(CONCAT('01/',@MES,'/',@ANO))
								)
		AND SPLANOAULA.DATA <= ISNULL((SELECT ([dbo].[FN_RETORNA_DATA_SAIDA_EB] (
			@CODCOLIGADA,@IDPERLET,@IDHABILITACAOFILIAL,@RA,@CODCURSO,@MES,@ANO)
		)),EOMONTH(CONCAT('01/',@MES,'/',@ANO)))
	END 
	ELSE IF @TIPO = 'S'
	BEGIN
		SELECT
			@HORA_ALUNO = (
				CASE
					WHEN MONTH(STURMA.DTFINAL) = @MES AND YEAR(STURMA.DTFINAL) = @ANO THEN SDISCGRADE.CH - SUM(DATEDIFF(HOUR,SHORARIO.HORAINICIAL,SHORARIO.HORAFINAL))
					ELSE SUM(DATEDIFF(HOUR,SHORARIO.HORAINICIAL,SHORARIO.HORAFINAL))
				END
			)
		FROM SMATRICPL WITH (NOLOCK)
		LEFT JOIN STURMA WITH (NOLOCK)
			ON SMATRICPL.CODCOLIGADA = STURMA.CODCOLIGADA
			AND SMATRICPL.CODFILIAL = STURMA.CODFILIAL
			AND SMATRICPL.CODTURMA = STURMA.CODTURMA
			AND SMATRICPL.IDPERLET = STURMA.IDPERLET
		LEFT JOIN SMATRICULA WITH (NOLOCK)
			ON SMATRICULA.CODCOLIGADA = SMATRICPL.CODCOLIGADA
			AND SMATRICULA.IDPERLET = SMATRICPL.IDPERLET
			AND SMATRICULA.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
			AND SMATRICULA.RA = SMATRICPL.RA
		LEFT JOIN SHABILITACAOFILIAL WITH (NOLOCK)
			ON SHABILITACAOFILIAL.CODCOLIGADA = SMATRICPL.CODCOLIGADA
			AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
		LEFT JOIN STURMADISC WITH (NOLOCK)
			ON STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
			AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
		LEFT JOIN SPLANOAULA WITH (NOLOCK)
			ON STURMADISC.CODCOLIGADA = SPLANOAULA.CODCOLIGADA
			AND STURMADISC.IDTURMADISC = SPLANOAULA.IDTURMADISC
		LEFT JOIN SHORARIO WITH (NOLOCK)
			ON SHORARIO.CODCOLIGADA = SPLANOAULA.CODCOLIGADA
			AND SHORARIO.CODHOR = SPLANOAULA.CODHOR
		LEFT JOIN SGRADE WITH (NOLOCK)
			ON SHABILITACAOFILIAL.CODCOLIGADA = SGRADE.CODCOLIGADA
			AND SHABILITACAOFILIAL.CODCURSO = SGRADE.CODCURSO
			AND SHABILITACAOFILIAL.CODHABILITACAO = SGRADE.CODHABILITACAO
			AND SHABILITACAOFILIAL.CODGRADE = SGRADE.CODGRADE
		LEFT JOIN SDISCGRADE WITH (NOLOCK)
			ON SDISCGRADE.CODCOLIGADA = SGRADE.CODCOLIGADA
			AND SDISCGRADE.CODDISC = STURMADISC.CODDISC
			AND SDISCGRADE.CODGRADE = SGRADE.CODGRADE
			AND SDISCGRADE.CODHABILITACAO = SGRADE.CODHABILITACAO
		WHERE 
			SMATRICPL.CODCOLIGADA = @CODCOLIGADA
		AND	SMATRICPL.IDPERLET = @IDPERLET
		AND	SMATRICPL.IDHABILITACAOFILIAL = @IDHABILITACAOFILIAL
		AND	SMATRICPL.RA = @RA
		AND STURMADISC.IDTURMADISC = @IDTURMADISC
		AND	MONTH(SPLANOAULA.DATA) = @MES
		AND	YEAR(SPLANOAULA.DATA) = @ANO
		AND SPLANOAULA.DATA >= ISNULL((SELECT datEfetivacaoMatricula FROM [dbo].[FN_RETORNA_DATA_MOV_MATRICULA_EB](
										@CODCOLIGADA,@IDPERLET,@IDHABILITACAOFILIAL,@RA))
									,EOMONTH(CONCAT('01/',@MES,'/',@ANO))
								)
		AND SPLANOAULA.DATA <= ISNULL((SELECT ([dbo].[FN_RETORNA_DATA_SAIDA_EB] (
			@CODCOLIGADA,@IDPERLET,@IDHABILITACAOFILIAL,@RA,@CODCURSO,@MES,@ANO)
		)),EOMONTH(CONCAT('01/',@MES,'/',@ANO)))
		GROUP BY STURMA.DTFINAL,SDISCGRADE.CH
	END
	ELSE IF @TIPO = 'D'
	BEGIN
		SELECT
			@HORA_ALUNO = CONVERT(INT,SDISCGRADE.CH / DATEDIFF(MONTH,
				STURMADISC.DTINICIAL,
				ISNULL(STURMADISC.DTFINAL,(SELECT [dbo].[FN_RETORNA_DATA_SAIDA_EB] (
					SMATRICPL.CODCOLIGADA,SMATRICPL.IDPERLET,SMATRICPL.IDHABILITACAOFILIAL,SMATRICPL.RA,SHABILITACAOFILIAL.CODCURSO,@MES,@ANO)
			))))	
		FROM SMATRICPL WITH (NOLOCK)
		INNER JOIN STURMA WITH (NOLOCK)
			ON SMATRICPL.CODCOLIGADA = STURMA.CODCOLIGADA
			AND SMATRICPL.CODFILIAL = STURMA.CODFILIAL
			AND SMATRICPL.CODTURMA = STURMA.CODTURMA
			AND SMATRICPL.IDPERLET = STURMA.IDPERLET
		INNER JOIN SMATRICULA WITH (NOLOCK)
			ON SMATRICULA.CODCOLIGADA = SMATRICPL.CODCOLIGADA
			AND SMATRICULA.IDPERLET = SMATRICPL.IDPERLET
			AND SMATRICULA.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
			AND SMATRICULA.RA = SMATRICPL.RA
		INNER JOIN SHABILITACAOFILIAL WITH (NOLOCK)
			ON SHABILITACAOFILIAL.CODCOLIGADA = SMATRICPL.CODCOLIGADA
			AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
		INNER JOIN STURMADISC WITH (NOLOCK)
			ON STURMADISC.CODCOLIGADA = SMATRICULA.CODCOLIGADA
			AND STURMADISC.IDTURMADISC = SMATRICULA.IDTURMADISC
		INNER JOIN SGRADE WITH (NOLOCK)
			ON SHABILITACAOFILIAL.CODCOLIGADA = SGRADE.CODCOLIGADA
			AND SHABILITACAOFILIAL.CODCURSO = SGRADE.CODCURSO
			AND SHABILITACAOFILIAL.CODHABILITACAO = SGRADE.CODHABILITACAO
			AND SHABILITACAOFILIAL.CODGRADE = SGRADE.CODGRADE
		INNER JOIN SDISCGRADE WITH (NOLOCK)
			ON SDISCGRADE.CODCOLIGADA = SGRADE.CODCOLIGADA
			AND SDISCGRADE.CODDISC = STURMADISC.CODDISC
			AND SDISCGRADE.CODGRADE = SGRADE.CODGRADE
			AND SDISCGRADE.CODHABILITACAO = SGRADE.CODHABILITACAO
		WHERE 
			SMATRICPL.CODCOLIGADA = @CODCOLIGADA
		AND	STURMADISC.DTINICIAL <= EOMONTH(CONCAT('01/',@MES,'/',@ANO))
		AND STURMADISC.DTFINAL >= ISNULL((SELECT ([dbo].[FN_RETORNA_DATA_SAIDA_EB] (
			SMATRICPL.CODCOLIGADA,SMATRICPL.IDPERLET,SMATRICPL.IDHABILITACAOFILIAL,SMATRICPL.RA,SHABILITACAOFILIAL.CODCURSO,@MES,@ANO)
		)),EOMONTH(CONCAT('01/',@MES,'/',@ANO)))
		AND	SMATRICPL.IDPERLET = @IDPERLET
		AND	SMATRICPL.IDHABILITACAOFILIAL = @IDHABILITACAOFILIAL
		AND	SMATRICPL.RA = @RA
		AND STURMADISC.IDTURMADISC = @IDTURMADISC
	END
	
	RETURN @HORA_ALUNO

END 

GO


